<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20210801162012_initial.cs" />
    <Compile Remove="Migrations\20210801162012_initial.Designer.cs" />
    <Compile Remove="Migrations\20210803092952_initial.cs" />
    <Compile Remove="Migrations\20210803092952_initial.Designer.cs" />
    <Compile Remove="Migrations\20210809081535_initial.cs" />
    <Compile Remove="Migrations\20210809081535_initial.Designer.cs" />
    <Compile Remove="Migrations\20210831170706_initial.cs" />
    <Compile Remove="Migrations\20210831170706_initial.Designer.cs" />
    <Compile Remove="Migrations\20210911192347_initial.cs" />
    <Compile Remove="Migrations\20210911192347_initial.Designer.cs" />
    <Compile Remove="Migrations\20211010163741_initial.cs" />
    <Compile Remove="Migrations\20211010163741_initial.Designer.cs" />
    <Compile Remove="Migrations\20211021095718_initial.cs" />
    <Compile Remove="Migrations\20211021095718_initial.Designer.cs" />
    <Compile Remove="Migrations\20211025115040_initial.cs" />
    <Compile Remove="Migrations\20211025115040_initial.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Certificate" Version="3.1.6" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.30" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.30">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="5.0.7" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.Design" Version="1.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="6.2.3" />
    <PackageReference Include="System.Drawing.Common" Version="5.0.2" />
    <PackageReference Include="System.Linq.Dynamic" Version="1.0.8" />
    <PackageReference Include="Telegram.Bot" Version="17.0.0" />
    <PackageReference Include="Telegram.Bot.Extensions.Polling" Version="1.0.2" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="8.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.10" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Model\settingsmodel\" />
    <Folder Include="Model\water\" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Microsoft.EntityFrameworkCore.Sqlite" />
    <None Remove="Model\water\" />
  </ItemGroup>
</Project>
